import { NextRequest, NextResponse } from 'next/server'
import { generateProductContent } from '@/lib/claude'
import { generateGuideMarkdown, createProductZip } from '@/lib/file-generator'
import { uploadZipToSupabase } from '@/lib/supabase'
import {
  updateProduct,
  enableProduct,
  listOfferCodes,
  deleteOfferCode,
  createOfferCode,
  BLUEGUM_PRODUCT_ID,
} from '@/lib/gumroad'

export const runtime = 'nodejs'

export async function POST(req: NextRequest) {
  const steps: string[] = []

  try {
    const { topic } = await req.json()

    if (!topic) {
      return NextResponse.json({ error: 'topic is required' }, { status: 400 })
    }

    // Step 1 — Generate content via Claude
    steps.push('Generating blueprint content with Claude...')
    const content = await generateProductContent(topic)
    steps.push(`✅ Guide generated: "${content.title}"`)

    // Step 2 — Build ZIP
    steps.push('Building ZIP package...')
    const guideMarkdown = generateGuideMarkdown(
      content.title,
      content.stepByStepGuide,
      content.faq,
      content.emailSequence,
      content.salesCopy
    )
    const zipBuffer = await createProductZip(
      guideMarkdown,
      'https://make.com/templates (update after building)',
      content.faq
    )
    steps.push(`✅ ZIP built (${Math.round(zipBuffer.byteLength / 1024)}kb)`)

    // Step 3 — Upload to Supabase
    steps.push('Uploading ZIP to Supabase storage...')
    const filename = `${Date.now()}-${topic.toLowerCase().replace(/\s+/g, '-')}.zip`
    const zipUrl = await uploadZipToSupabase(zipBuffer, filename)
    steps.push(`✅ Uploaded: ${zipUrl}`)

    // Step 4 — Update existing Gumroad product
    steps.push(`Updating Gumroad product (${BLUEGUM_PRODUCT_ID})...`)
    const description = `
<h2>${content.title}</h2>

<p>${content.description}</p>

${content.longDescription}

<h3>📦 Download includes:</h3>
<ul>
  <li>📘 Complete step-by-step build guide</li>
  <li>📧 3-part email sequence</li>
  <li>❓ FAQ document</li>
  <li>💬 Sales copy</li>
  <li>🔗 Make.com template link</li>
</ul>

<p><strong>Download:</strong> <a href="${zipUrl}">${zipUrl}</a></p>

<p><em>Generated by BlueGum Studio</em></p>
`.trim()

    const product = await updateProduct(BLUEGUM_PRODUCT_ID, {
      name: content.title,
      description,
      price: 700,
      published: true,
    })
    steps.push(`✅ Product updated: ${product.short_url}`)

    // Step 5 — Ensure published
    steps.push('Ensuring product is published...')
    await enableProduct(BLUEGUM_PRODUCT_ID)
    steps.push('✅ Product is live')

    // Step 6 — Refresh LAUNCH20 offer code
    steps.push('Refreshing LAUNCH20 offer code...')
    const existingCodes = await listOfferCodes(BLUEGUM_PRODUCT_ID)
    const oldLaunch = existingCodes.find((c) => c.name === 'LAUNCH20')
    if (oldLaunch) await deleteOfferCode(BLUEGUM_PRODUCT_ID, oldLaunch.id)
    const offerCode = await createOfferCode(BLUEGUM_PRODUCT_ID, {
      name: 'LAUNCH20',
      amount_off: 20,
      percent_off: true,
      max_purchase_count: 50,
    })
    steps.push(`✅ Offer code: ${offerCode.name} (${offerCode.amount_off}% off)`)

    steps.push('🚀 Blueprint deployed successfully!')

    return NextResponse.json({
      success: true,
      productUrl: product.short_url || `https://otutubelle.gumroad.com/l/${BLUEGUM_PRODUCT_ID}`,
      zipUrl,
      productId: BLUEGUM_PRODUCT_ID,
      offerCode: offerCode.name,
      title: content.title,
      steps,
    })
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err)
    steps.push(`❌ Error: ${message}`)
    return NextResponse.json({ error: message, steps }, { status: 500 })
  }
}
