import { NextRequest, NextResponse } from 'next/server'
import { generateBlueprintContent } from '@/lib/claude'
import { buildZip } from '@/lib/file-generator'
import { uploadZipToSupabase } from '@/lib/supabase'
import {
  updateProduct,
  enableProduct,
  listOfferCodes,
  deleteOfferCode,
  createOfferCode,
  BLUEGUM_PRODUCT_ID,
} from '@/lib/gumroad'

export const runtime = 'nodejs'

export async function POST(req: NextRequest) {
  const steps: string[] = []

  try {
    const { topic, searchResults } = await req.json()

    if (!topic) {
      return NextResponse.json({ error: 'topic is required' }, { status: 400 })
    }

    // Step 1 — Generate guide content via Claude
    steps.push('Generating blueprint content with Claude...')
    const content = await generateBlueprintContent(topic, searchResults || [])
    steps.push(`✅ Guide generated: "${content.title}"`)

    // Step 2 — Build ZIP
    steps.push('Building ZIP package...')
    const zipBuffer = await buildZip(content)
    steps.push(`✅ ZIP built (${Math.round(zipBuffer.byteLength / 1024)}kb)`)

    // Step 3 — Upload to Supabase
    steps.push('Uploading ZIP to Supabase storage...')
    const filename = `${Date.now()}-${topic.toLowerCase().replace(/\s+/g, '-')}.zip`
    const zipUrl = await uploadZipToSupabase(Buffer.from(zipBuffer), filename)
    steps.push(`✅ Uploaded: ${zipUrl}`)

    // Step 4 — Update the existing Gumroad product
    steps.push(`Updating Gumroad product (${BLUEGUM_PRODUCT_ID})...`)
    const description = `
<h2>${content.title}</h2>

<p>${content.summary}</p>

<h3>What's inside:</h3>
<ul>
${content.sections.map((s: string) => `  <li>${s}</li>`).join('\n')}
</ul>

<h3>Download includes:</h3>
<ul>
  <li>📘 Complete setup guide (Markdown)</li>
  <li>🔗 Make.com template link</li>
  <li>❓ FAQ document</li>
  <li>📄 README</li>
</ul>

<p><strong>Download ZIP:</strong> <a href="${zipUrl}">${zipUrl}</a></p>

<p><em>Generated by BlueGum Studio — AI-powered Make.com blueprint generator</em></p>
`.trim()

    const product = await updateProduct(BLUEGUM_PRODUCT_ID, {
      name: content.title,
      description,
      price: 700, // $7.00 in cents
      published: true,
    })
    steps.push(`✅ Product updated: ${product.short_url}`)

    // Step 5 — Enable/publish
    steps.push('Ensuring product is published...')
    await enableProduct(BLUEGUM_PRODUCT_ID)
    steps.push('✅ Product is live')

    // Step 6 — Refresh offer code (delete old LAUNCH20, create fresh one)
    steps.push('Refreshing LAUNCH20 offer code...')
    const existingCodes = await listOfferCodes(BLUEGUM_PRODUCT_ID)
    const oldLaunch = existingCodes.find((c) => c.name === 'LAUNCH20')
    if (oldLaunch) {
      await deleteOfferCode(BLUEGUM_PRODUCT_ID, oldLaunch.id)
    }
    const offerCode = await createOfferCode(BLUEGUM_PRODUCT_ID, {
      name: 'LAUNCH20',
      amount_off: 20,
      percent_off: true,
      max_purchase_count: 50,
    })
    steps.push(`✅ Offer code ready: ${offerCode.name} (${offerCode.amount_off}% off)`)

    // Step 7 — Done
    steps.push('🚀 Blueprint deployed successfully!')

    return NextResponse.json({
      success: true,
      productUrl: product.short_url || `https://otutubelle.gumroad.com/l/${BLUEGUM_PRODUCT_ID}`,
      zipUrl,
      productId: BLUEGUM_PRODUCT_ID,
      offerCode: offerCode.name,
      title: content.title,
      steps,
    })
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err)
    steps.push(`❌ Error: ${message}`)
    return NextResponse.json({ error: message, steps }, { status: 500 })
  }
}
