import JSZip from 'jszip'

// Replaces pdfkit entirely — generates a rich markdown guide instead of PDF.
// pdfkit fails in Vercel serverless because it can't locate its bundled font files.
export function generateGuideMarkdown(
  title: string,
  stepByStepGuide: string,
  faq: string[],
  emailSequence: Array<{ subject: string; body: string }>,
  salesCopy: string
): string {
  const line = '─'.repeat(60)

  const emailSection = emailSequence?.length
    ? `\n\n${line}\n## EMAIL SEQUENCE\n${line}\n\n` +
      emailSequence.map((e, i) =>
        `### Email ${i + 1}: ${e.subject}\n\n${e.body}`
      ).join('\n\n---\n\n')
    : ''

  const faqSection = faq?.length
    ? `\n\n${line}\n## FAQ\n${line}\n\n` +
      faq.map((item, i) => `**${i + 1}.** ${item}`).join('\n\n')
    : ''

  return [
    `# ${title}`,
    `\n> Generated by BlueGum Studio — Make.com Blueprint Generator\n`,
    line,
    `## STEP-BY-STEP BUILD GUIDE`,
    line,
    '',
    stepByStepGuide,
    faqSection,
    emailSection,
    `\n\n${line}`,
    `## SALES COPY`,
    line,
    salesCopy ?? '',
    `\n\n${line}`,
    `*After building your Make.com workflow, update the template link in your Gumroad product.*`,
  ].join('\n')
}

export async function createProductZip(
  guideMarkdown: string,
  templateLink: string,
  faq: string[]
): Promise<Buffer> {
  const zip = new JSZip()

  zip.file('setup-guide.md', guideMarkdown)
  zip.file('template-link.txt', templateLink)
  zip.file('faq.txt', faq.join('\n\n'))
  zip.file('README.txt', [
    'BLUEPRINT PACKAGE',
    '=================',
    '',
    'Files included:',
    '  setup-guide.md    — Full step-by-step build guide + FAQ + email sequence',
    '  template-link.txt — Make.com template link (update after building)',
    '  faq.txt           — Frequently asked questions',
    '',
    'Generated by BlueGum Studio',
  ].join('\n'))

  return Buffer.from(await zip.generateAsync({ type: 'nodebuffer' }))
}
